name: urlshortener
description: "URL Shortly Shortener"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.2
  icons_launcher: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.jpg"
  windows:
    generate: true
    image_path: "assets/logo.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo.jpg"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/logo.jpg"

icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true